name: Django CI pipline #name of the pipeline
on: #trigger
  push:
    branches:       #automatic trigger
      - master
  workflow_dispatch: #manual trigger

jobs:
  test: #name of the job u can name it anything u want 
    runs-on: ubuntu-latest #runner --> machine where my pipeline will run 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3   #download the code 
      - name: setup python  
        uses: actions/setup-python@v4 #install the python
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install django
      - name: run server check #run server and tests response
        run: |
          python manage.py ruserver & 
          sleep 5
          curl http://127.0.0.1.8000 || echo "server failed"

